"""Opper SDK for Python."""

from ._client import Opper
from .agent import (
    AbortError,
    Agent,
    AgentError,
    AgentStream,
    AgentStreamEvent,
    AgentTool,
    AggregatedUsage,
    Conversation,
    Hooks,
    IterationEndEvent,
    IterationStartEvent,
    MaxIterationsError,
    ReasoningDeltaEvent,
    ResultEvent,
    RetryPolicy,
    RunMeta,
    RunOptions,
    RunResult,
    StreamErrorEvent,
    TextDeltaEvent,
    ToolCallRecord,
    ToolEndEvent,
    ToolProvider,
    ToolStartEvent,
    merge_hooks,
    tool,
)
from .types import (
    ApiError,
    ArtifactStatus,
    AuthenticationError,
    BadRequestError,
    CompleteChunk,
    ContentChunk,
    DoneChunk,
    ErrorChunk,
    ErrorDetail,
    InternalServerError,
    MediaResponse,
    Model,
    ModelConfig,
    NotFoundError,
    PendingOperation,
    RateLimitError,
    RequestOptions,
    ResponseMeta,
    RunResponse,
    SpanHandle,
    StreamChunk,
    ToolCallDeltaChunk,
    ToolCallStartChunk,
    UsageInfo,
)

__all__ = [
    "Opper",
    # Agent SDK
    "Agent",
    "AgentStream",
    "Conversation",
    "tool",
    "AgentTool",
    "Hooks",
    "RetryPolicy",
    "RunResult",
    "RunMeta",
    "RunOptions",
    "AggregatedUsage",
    "ToolCallRecord",
    "ToolProvider",
    "merge_hooks",
    # Agent stream events
    "AgentStreamEvent",
    "IterationStartEvent",
    "TextDeltaEvent",
    "ReasoningDeltaEvent",
    "ToolStartEvent",
    "ToolEndEvent",
    "IterationEndEvent",
    "ResultEvent",
    "StreamErrorEvent",
    # Agent errors
    "AgentError",
    "MaxIterationsError",
    "AbortError",
    # Errors
    "ApiError",
    "BadRequestError",
    "AuthenticationError",
    "NotFoundError",
    "RateLimitError",
    "InternalServerError",
    "ErrorDetail",
    # Response types
    "ArtifactStatus",
    "MediaResponse",
    "Model",
    "ModelConfig",
    "PendingOperation",
    "RequestOptions",
    "RunResponse",
    "ResponseMeta",
    "UsageInfo",
    "SpanHandle",
    # Stream chunks
    "StreamChunk",
    "ContentChunk",
    "ToolCallStartChunk",
    "ToolCallDeltaChunk",
    "DoneChunk",
    "ErrorChunk",
    "CompleteChunk",
]
